[package]
name = "syntax"
description = "Text to normalised syntactic spans."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
line-index.workspace = true
syntect.workspace = true
two-face.workspace = true

[lints]
workspace = true
